// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 🚀 AJUSTE DE DEVOPS: Fallback para não quebrar o Docker Build quando a variável não existir
    url: process.env.DATABASE_URL || "postgresql://usuario:senha@localhost:5432/banco_falso",
  },
});